/**
 * Sarvatobhadra Chakra — standard 9×9 layout + deterministic vedha engine.
 *
 * The layout is represented explicitly rather than generated by a heuristic
 * filler.  This matters because vedha is geometric: changing one cell changes
 * the interpretation of every ray crossing it.  School/edition variants are
 * therefore separate layout IDs instead of being silently merged.
 */
import ruleData from '../../../dataset/used/core/system-rules.json' with { type: 'json' };

const WEEKDAYS=Object.freeze(ruleData.sarvatobhadra.WEEKDAYS);
const TITHI_GROUPS=Object.freeze(ruleData.sarvatobhadra.TITHI_GROUPS);
const SIGNS=Object.freeze(ruleData.sarvatobhadra.SIGNS);
import layoutData from '../../../dataset/used/core/sarvatobhadra-layout.json' with { type: 'json' };
const NAKSHATRAS_28=Object.freeze(layoutData.nakshatras28);
const STANDARD_ROWS = layoutData['standard-9x9'];
const GRID=Object.freeze(STANDARD_ROWS.map((row,r)=>row.map((item,c)=>Object.freeze({row:r,col:c,type:item[0],value:item[1]}))));
const BENEFICS=new Set(['Moon','Mercury','Jupiter','Venus']);
const MALEFICS=new Set(['Sun','Mars','Saturn','Rahu','Ketu']);
const MOTION_DIRECTION=Object.freeze(layoutData.motionDirection);

function normalizeSign(value){if(typeof value==='number')return SIGNS[((value%12)+12)%12];return SIGNS.includes(value)?value:null;}
function tithiGroup(n){for(const [name,values] of Object.entries(TITHI_GROUPS))if(values.includes(Number(n)))return name;return null;}
function locate(type,value){for(const row of GRID)for(const cell of row)if(cell.type===type&&cell.value===value)return [cell.row,cell.col];return null;}
function ray(start,dir){const out=[];let r=start[0]+dir[0],c=start[1]+dir[1];while(r>=0&&r<9&&c>=0&&c<9){out.push(GRID[r][c]);r+=dir[0];c+=dir[1];}return out;}
function classifyPlanet(p){if(BENEFICS.has(p?.name))return 'BENEFIC';if(MALEFICS.has(p?.name))return 'MALEFIC';return 'NEUTRAL';}
function directionFor(p){if(p?.retrograde===true)return MOTION_DIRECTION.retrograde;if(['Sun','Moon'].includes(p?.name))return MOTION_DIRECTION.direct;return MOTION_DIRECTION.front;}
function deriveNakshatra(lon){return Number.isFinite(Number(lon))?NAKSHATRAS_28[Math.floor((((Number(lon)%360)+360)%360)/(360/27))%27]:null;}

export function buildSarvatobhadraChakra({moonNakshatra,moonSign,weekday,tithi,planetPositions=[],nameSyllable=null,layoutVariant='standard-9x9'}={}){
  if(layoutVariant!=='standard-9x9')throw new Error(`Unsupported Sarvatobhadra layout variant: ${layoutVariant}`);
  if(moonNakshatra!=null && !NAKSHATRAS_28.includes(moonNakshatra))throw new Error(`Unknown Sarvatobhadra Nakshatra: ${moonNakshatra}`);
  const janmaNak=locate('nakshatra',moonNakshatra);
  const natalTargets=[];
  if(janmaNak)natalTargets.push({type:'nakshatra',value:moonNakshatra});
  const sign=normalizeSign(moonSign);if(sign)natalTargets.push({type:'rashi',value:sign});
  const tg=tithiGroup(typeof tithi==='object'?tithi?.number:tithi);if(tg)natalTargets.push({type:'tithi',value:tg});
  if(weekday!=null)natalTargets.push({type:'weekday',value:typeof weekday==='number'?WEEKDAYS[weekday]:weekday});
  if(nameSyllable!=null)natalTargets.push({type:'nameSyllable',value:String(nameSyllable)});

  const structuralVedha = janmaNak ? [
    ray(janmaNak,[0,1]),
    ray(janmaNak,[1,0]),
    ray(janmaNak,[1,1])
  ].map((cells,i)=>({source:'structural',sourceNakshatra:moonNakshatra,direction:[[0,1],[1,0],[1,1]][i],cells:cells.map(c=>({...c,hitType:c.type,hitValue:c.value}))})) : [];
  const vedha=[...structuralVedha];
  for(const p of planetPositions){
    const nak=p.nakshatra??deriveNakshatra(p.siderealLon);
    const pos=locate('nakshatra',nak); if(!pos)continue;
    const dir=directionFor(p);
    const cells=ray(pos,dir);
    const row={planet:p.name,sourceNakshatra:nak,motion:p.retrograde?'retrograde':(['Sun','Moon'].includes(p.name)?'direct':'front'),direction:dir,polarity:classifyPlanet(p),cells:cells.map(c=>({...c,hitType:c.type,hitValue:c.value}))};
    row.targets=row.cells.filter(c=>natalTargets.some(t=>t.type===c.type&&t.value===c.value));
    row.severity=row.targets.length>=4?'EXTREME':row.targets.length===3?'HIGH':row.targets.length===2?'MODERATE':row.targets.length===1?'LOW':'NONE';
    vedha.push(row);
  }
  const activeVedha=vedha.flatMap(v=>(v.targets||[]).map(t=>({planet:v.planet||null,polarity:v.polarity||'STRUCTURAL',sourceNakshatra:v.sourceNakshatra,motion:v.motion||'structural',target:t,severity:v.severity||'STRUCTURAL'})));
  return {
    status:'VERIFIED_LAYOUT',system:'Sarvatobhadra Chakra',layoutVariant,
    dimensions:{rows:9,cols:9,cells:81,nakshatras:28,rashis:12,vowels:16,consonants:20,tithiGroups:5},
    grid:GRID.map(row=>row.map(c=>({...c}))),
    nakshatras:NAKSHATRAS_28.map((name,i)=>({index:i+1,name,active:name===moonNakshatra,position:locate('nakshatra',name)})),
    center:{nakshatra:moonNakshatra,sign,weekday:typeof weekday==='number'?WEEKDAYS[weekday]:weekday,tithiGroup:tg,nameSyllable},
    natalTargets,
    vedha,
    activeVedha,
    interpretation:{beneficPlanets:[...BENEFICS],maleficPlanets:[...MALEFICS],rule:'Each source nakshatra emits a direction-dependent vedha ray; affected natal cells are reported without converting the result into an unsupported probability.'},
    evidence:{layout:'standard-9x9 explicit classical-layout variant',vedha:'directional geometric calculation',limitations:'Sarvatobhadra has layout/lineage variants; this result is explicitly versioned.'}
  };
}

export { NAKSHATRAS_28 };
