/**
 * header.js — Prints the report title box + birth-detail summary.
 *
 * Section 3 (Basic Details): every field the person asked for is printed
 * here. Anything this offline engine cannot reliably calculate (DST,
 * War Time, Samvat year, birth-time confidence/source when not supplied)
 * is shown honestly as NOT_AVAILABLE with a reason — never invented.
 */
import { box, kv, sub, C } from '../console-ui.js';
import { normalizeElapsedMs } from './reportTiming.js';

// Prints either a plain value, or a { status: 'NOT_AVAILABLE', reason }
// object as a clearly-marked "not available" line — used for every field
// this engine cannot back with a real calculation or a real user answer.
function kvOrNA(label, val) {
  if (val && typeof val === 'object' && val.status === 'NOT_AVAILABLE') {
    kv(label, C.dim + 'STATUS = NOT_AVAILABLE' + C.reset);
    console.log('  ' + C.dim + `  REASON = ${val.reason}` + C.reset);
  } else if (val && typeof val === 'object' && ['PROVIDED', 'AVAILABLE', 'AUTOMATIC_OR_NOT_REQUIRED'].includes(val.status)) {
    const display = val.vikramSamvat != null || val.shakaSamvat != null
      ? `Vikram ${val.vikramSamvat} / Shaka ${val.shakaSamvat} (${val.system})`
      : val.value ?? val.status;
    kv(label, display);
    if (val.note) console.log('  ' + C.dim + `  NOTE = ${val.note}` + C.reset);
  } else {
    kv(label, val ?? '-');
  }
}

export function printHeader(R, elapsedMs) {
  const m = R.meta;
  const elapsed = normalizeElapsedMs(elapsedMs);
  box('🕉️   COMPLETE VEDIC JYOTISH REPORT (जन्म कुंडली - सम्पूर्ण विवरण)  🕉️');
  console.log('');

  sub('A1. Identity');
  kv('Name / नाम', m.name);
  kv('Gender / लिंग', m.sex === 'F' ? 'Female / स्त्री' : 'Male / पुरुष');

  console.log('');
  sub('A2. Date, Time & Place of Birth');
  kv('Date of Birth', `${String(m.day).padStart(2, '0')}-${String(m.month).padStart(2, '0')}-${m.year}`);
  kv('Day of Birth', m.weekday ? `${m.weekday}${m.weekdayHindi ? ' / ' + m.weekdayHindi : ''}` : '-');
  kv('Exact Birth Time', `${String(m.hour).padStart(2, '0')}:${String(m.min).padStart(2, '0')}:${String(m.sec).padStart(2, '0')} (local clock time)`);
  kv('Birth Place', m.place || (Number.isFinite(Number(m.lat)) && Number.isFinite(Number(m.lon)) ? `Coordinates only (Lat ${m.lat}, Lon ${m.lon})` : '-'));
  kv('Latitude', m.lat);
  kv('Longitude', m.lon);
  kv('Timezone', `UTC ${m.tz >= 0 ? '+' : ''}${m.tz}`);

  console.log('');
  sub('A3. Time Foundations');
  kv('UTC/GMT at Birth', m.utcAtBirth);
  kv('Local Mean Time', `${m.localMeanTime}  (true solar time at this longitude)`);
  kv('Local Time Correction', `${m.localTimeCorrectionMinutes >= 0 ? '+' : ''}${m.localTimeCorrectionMinutes} min  (LMT vs. zone standard-meridian clock)`);
  kvOrNA('DST Correction', m.dstCorrection);
  kvOrNA('War Time Correction', m.warTimeCorrection);
  kv('Ishtkaal (इष्टकाल)', `${m.ishtaKaal.formatted}  (${m.ishtaKaal.elapsedSinceSunrise} elapsed since sunrise)`);

  console.log('');
  sub('A4. Astronomical Foundations');
  kv('Julian Day', m.JD);
  kv('Ayanamsa System', `${m.ayanamsaMode}  (value: ${R.ayanamsa.value}°)`);
  kv('Obliquity of Ecliptic', `${m.obliquity}°`);
  kv('Sidereal Time', m.siderealTime);
  kv('Calendar System (input)', m.calendarSystem.inputCalendar);
  kv('Calendar System (Panchang)', m.calendarSystem.panchangCalendar);
  kvOrNA('  Vikram/Shaka Samvat Year', m.calendarSystem.samvatYear);
  kv('Sunrise (birthplace)', m.sunrise);
  kv('Sunset (birthplace)', m.sunset);

  console.log('');
  sub('A5. Input Reliability');
  kvOrNA('Birth-Time Confidence', m.birthTimeConfidence);
  kvOrNA('Source/Input Quality', m.sourceQuality);

  console.log('');
  sub('A6. Report Metadata');
  kv('Report Generated', new Date(m.generatedAt).toLocaleString());
  kv('Calculation Time', `${elapsed.toFixed(3)} ms`);
  kv('Astronomy Provider', R.ephemerisProvider?.id || 'unknown');
  kv('Astronomy Precision', R.ephemerisProvider?.precision || 'unknown');
}

export function printFooter() {
  box('✨  END OF REPORT — सम्पूर्ण रिपोर्ट समाप्त  ✨');
  console.log(C.dim + '\nGenerated by JyotiVeda V1 — Vedic Astrology Engine (astronomy provider is reported above; no provider is silently substituted)\n' + C.reset);
}
