import { calculateChart } from '../engine/InternalCalculationEngine.js';
import { calculateNumerology } from '../numerology/numerology.js';
import { buildDailyHoroscope } from '../horoscope/daily_horoscope.js';
import { calcPanchanga } from '../panchanga/panchanga.js';
import { getAllPlanetPositions } from '../astronomy/vsop87.js';
import { julianDay, deltaT, mod360, signOf, lahiriAyanamsa } from '../astronomy/utils.js';
import { SIGNS, NAKSHATRAS, NAKSHATRA_LORDS, SIGN_LORDS, NATURAL_FRIENDS } from '../astronomy/constants.js';
import { getTransitPositions, calcTransitOverlay } from '../transit/transits.js';
import { calcMangalDosha, calcKalsarpaDosha } from '../dosha/doshas.js';
import { calcAccurateSadeSati } from '../dosha/sade_sati_accurate.js';
import panchangData from '../../dataset/used/core/panchang_calculator_v15.json' with { type: 'json' };

const clean = s => String(s ?? '').toUpperCase().replace(/[^A-Z]/g, '');
const digitSum = value => String(value).replace(/\D/g,'').split('').reduce((a,d)=>a+Number(d),0);
const reduce = n => { let x = Math.abs(Number(n)); while (x > 9 && ![11,22,33].includes(x)) x = digitSum(x); return x; };
const dateObj = s => { const d = new Date(`${s}T00:00:00Z`); if (Number.isNaN(d.getTime())) throw new Error(`Invalid date: ${s}`); return d; };
const jdForDate = s => { const d=dateObj(s); return julianDay(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate(),0); };
function validateBirth(b){ if(!b || typeof b!=='object') throw new Error('birth object required'); return b; }
function nameScore(a,b){ const x=clean(a), y=clean(b); if(!x||!y) throw new Error('Both names are required'); const sa=new Set(x), sb=new Set(y); const common=[...sa].filter(c=>sb.has(c)).length; return Math.round(100*(common/Math.max(sa.size,sb.size))); }
function flames(a,b){ const x=clean(a), y=clean(b); if(!x||!y) throw new Error('Both names are required'); const counts={}; for(const c of x) counts[c]=(counts[c]||0)+1; for(const c of y) if(counts[c]) counts[c]--; const remaining=Object.values(counts).reduce((s,n)=>s+n,0)+[...y].reduce((s,c)=>s+(counts[c]===undefined?1:0),0); const labels=['Friends','Lovers','Affection','Marriage','Enemies','Siblings']; let idx=0; let pool=labels.slice(); while(pool.length>1){ idx=(idx+remaining-1)%pool.length; pool.splice(idx,1); } return {remainingCount:remaining,result:pool[0]}; }
function getSevenKaraka(planets){ const p=planets.filter(x=>['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn'].includes(x.name)).map(x=>({...x,degree:x.siderealLon%30})).sort((a,b)=>b.degree-a.degree); return {atmakaraka:p[0]?.name||null,darakaraka:p[p.length-1]?.name||null,ranking:p.map((x,i)=>({rank:i+1,planet:x.name,degree:x.degree}))}; }
function moonPhase(date){ const jd=jdForDate(date); const pos=getAllPlanetPositions(jd,0); const elong=mod360(pos.Moon.longitude-pos.Sun.longitude); const age=elong/12.19075; const illumination=(1-Math.cos(elong*Math.PI/180))/2; const names=['New Moon','Waxing Crescent','First Quarter','Waxing Gibbous','Full Moon','Waning Gibbous','Last Quarter','Waning Crescent']; const idx=Math.min(7,Math.floor(((elong+22.5)%360)/45)); return {date,julianDay:jd,elongationDegrees:Number(elong.toFixed(6)),lunarAgeDays:Number(age.toFixed(3)),illumination:Number(illumination.toFixed(6)),phase:names[idx]}; }
function choghadiya(p){ const {sunrise,sunset,vara}=p; if(!sunrise||!sunset) return []; const dayLen=sunset-sunrise, nightLen=(sunrise+1)-sunset; const key=vara?.name || 'Sunday'; const dayNames=panchangData.choghadiya.day[key] || panchangData.choghadiya.day.Sunday; const nightNames=panchangData.choghadiya.night[key] || panchangData.choghadiya.night.Sunday; return [...Array(8)].map((_,i)=>({index:i+1,period:'day',name:dayNames[i],start:sunrise+i*dayLen/8,end:sunrise+(i+1)*dayLen/8})).concat([...Array(8)].map((_,i)=>({index:i+9,period:'night',name:nightNames[i],start:sunset+i*nightLen/8,end:sunset+(i+1)*nightLen/8}))); }
function hora(p){ const {sunrise,sunset}=p; if(!sunrise||!sunset) return []; const dayLen=sunset-sunrise; const planets=['Sun','Venus','Mercury','Moon','Saturn','Jupiter','Mars']; const dayIndex=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn']; const vara=dayIndex.indexOf(p.vara?.lord); const start=vara<0?0:vara; return [...Array(24)].map((_,i)=>({hora:i+1,planet:planets[(start+i)%7],start:i<12?sunrise+i*dayLen/12:sunset+(i-12)*(1-dayLen)/12,end:i<12?sunrise+(i+1)*dayLen/12:sunset+(i-11)*(1-dayLen)/12})); }
export async function runCalculator(id,input={}){
  switch(id){
    case 'love': return {score:nameScore(input.nameA,input.nameB),names:[input.nameA,input.nameB],method:'deterministic shared-letter similarity'};
    case 'name-compatibility': return {score:nameScore(input.nameA,input.nameB),names:[input.nameA,input.nameB],method:'deterministic shared-letter similarity'};
    case 'flames': return flames(input.nameA,input.nameB);
    case 'numerology': return calculateNumerology(input.name,input.dob);
    case 'mulank': { const d=input.dob?.day; if(!d) throw new Error('dob.day required'); return {rawDay:d,mulank:reduce(d)}; }
    case 'destiny-number': { const n=calculateNumerology(input.name,{year:2000,month:1,day:1}); return {name:input.name,destiny:n.numbers.destiny}; }
    case 'mobile-number': { const digits=String(input.mobile??'').replace(/\D/g,''); if(!digits) throw new Error('mobile required'); return {mobileLast4:digits.slice(-4),digitSum:digitSum(digits),number:reduce(digitSum(digits))}; }
    case 'lucky-vehicle': { const v=String(input.vehicleNumber??'').replace(/\D/g,''); if(!v) throw new Error('vehicleNumber required'); const n=reduce(digitSum(v)); const birth=input.dob?.day?reduce(input.dob.day):null; return {vehicleNumber:v,luckyNumber:n,birthNumber:birth,compatibility:birth?Math.max(0,100-Math.abs(n-birth)*12):null}; }
    case 'lo-shu-grid': { const d=input.dob; if(!d) throw new Error('dob required'); const digits=String(d.year).padStart(4,'0')+String(d.month).padStart(2,'0')+String(d.day).padStart(2,'0'); const grid={1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[]}; for(const ch of digits) if(ch!=='0') grid[ch].push(Number(ch)); return {grid,counts:Object.fromEntries(Object.entries(grid).map(([k,v])=>[k,v.length]))}; }
    case 'lucky-name': { const n=calculateNumerology(input.name,input.dob); const lucky=n.luckyNumbers; return {name:n.name,destiny:n.numbers.destiny.value,mulank:n.numbers.driver.value,luckyNumbers:lucky,score:lucky.includes(n.numbers.driver.value)?100:70}; }
    case 'age': { const b=dateObj(input.dob), a=input.asOf?dateObj(input.asOf):new Date(); let years=a.getUTCFullYear()-b.getUTCFullYear(); const before=a.getUTCMonth()<b.getUTCMonth()||(a.getUTCMonth()===b.getUTCMonth()&&a.getUTCDate()<b.getUTCDate()); if(before) years--; const anniversary=new Date(Date.UTC(a.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate())); const prev=before?new Date(Date.UTC(a.getUTCFullYear()-1,b.getUTCMonth(),b.getUTCDate())):anniversary; const days=Math.floor((a-prev)/86400000); return {dob:input.dob,asOf:a.toISOString().slice(0,10),completedYears:years,daysSinceLastBirthday:days}; }
    case 'ayanamsa': { const jd=input.date?jdForDate(input.date):jdForDate(new Date().toISOString().slice(0,10)); return {date:input.date||new Date().toISOString().slice(0,10),ayanamsaDegrees:Number(lahiriAyanamsa(jd).toFixed(6)),method:'Lahiri ayanamsa'}; }
    case 'sun-sign': case 'rashi': case 'rising-sign': case 'nakshatra': case 'dasha': case 'natal-chart': case 'mangal-dosha': case 'kaal-sarp-dosh': case 'ishta-devata': case 'atmakaraka-darakaraka': case 'friendship': case 'transit-chart': case 'sade-sati': { validateBirth(input.birth); const chart=await calculateChart(input.birth); if(id==='sun-sign') { const x=chart.planets?.find(p=>p.name==='Sun'); return {sign:SIGNS[signOf(x?.siderealLon||0)],longitude:x?.siderealLon}; } if(id==='rashi') { const x=chart.planets?.find(p=>p.name==='Moon'); return {rashi:SIGNS[signOf(x?.siderealLon||0)],longitude:x?.siderealLon}; } if(id==='rising-sign') return {risingSign:chart.ascendant?.sign,longitude:Number(chart.ascendant?.lon)}; if(id==='nakshatra'){const m=chart.planets?.find(p=>p.name==='Moon'); return {nakshatra:m?.nakshatra,pada:m?.pada,moonSign:SIGNS[signOf(m?.siderealLon||0)]};} if(id==='atmakaraka-darakaraka') return getSevenKaraka(chart.planets||[]); if(id==='natal-chart') return chart; if(id==='dasha') return chart.dasha; if(id==='mangal-dosha') return calcMangalDosha(chart.planets,Number(chart.ascendant?.lon),chart.planets.find(p=>p.name==='Moon')?.siderealLon,chart.planets.find(p=>p.name==='Venus')?.siderealLon); if(id==='kaal-sarp-dosh') return calcKalsarpaDosha(chart.planets); if(id==='ishta-devata') return chart.ishtaDevata||null; if(id==='friendship'){ if(!input.birthA||!input.birthB) throw new Error('birthA and birthB are required'); const b=await calculateChart(input.birthB); const ma=chart.planets?.find(p=>p.name==='Moon'); const mb=b.planets?.find(p=>p.name==='Moon'); const sa=signOf(ma?.siderealLon||0), sb=signOf(mb?.siderealLon||0); const la=SIGN_LORDS[SIGNS[sa]], lb=SIGN_LORDS[SIGNS[sb]]; const friends=(NATURAL_FRIENDS[la]||[]).includes(lb); const enemies=(NATURAL_FRIENDS[la]||[]).includes(lb)===false; return {personA:{moonSign:SIGNS[sa],signLord:la},personB:{moonSign:SIGNS[sb],signLord:lb},score:friends?85:enemies?55:70}; } if(id==='transit-chart'){const jd=input.date?jdForDate(input.date):julianDay(new Date().getUTCFullYear(),new Date().getUTCMonth()+1,new Date().getUTCDate(),0); return {transits:getTransitPositions(jd),overlay:calcTransitOverlay(chart.planets,jd,signOf(chart.planets.find(p=>p.name==='Moon')?.siderealLon||0))};} const moonSignIdx=signOf(chart.planets.find(p=>p.name==='Moon')?.siderealLon||0); const nowJD=input.date?jdForDate(input.date):julianDay(new Date().getUTCFullYear(),new Date().getUTCMonth()+1,new Date().getUTCDate(),0); return calcAccurateSadeSati(moonSignIdx,nowJD,jd=>getTransitPositions(jd).Saturn.siderealLon); }
    case 'moon-phase': return moonPhase(input.date);
    default: throw new Error(`Unknown calculator: ${id}`);
  }
}

export function buildPanchangFeature(feature,input={}){ let date=input.date||new Date().toISOString().slice(0,10); if(feature==='tomorrow-panchang'){const d=dateObj(date); d.setUTCDate(d.getUTCDate()+1); date=d.toISOString().slice(0,10);} const jd=jdForDate(date); const b=input.birth||{}; const lat=Number.isFinite(b.lat)?b.lat:Number(input.lat??0); const lon=Number.isFinite(b.lon)?b.lon:Number(input.lon??0); const tz=Number.isFinite(b.tz)?b.tz:Number(input.tz??0); const pos=getAllPlanetPositions(jd,0); const p=calcPanchanga(jd,pos.Sun.longitude,pos.Moon.longitude,lat,lon,tz,pos.Moon.speed,pos.Sun.speed); if(feature==='choghadiya') return {...p,choghadiya:choghadiya(p)}; if(feature==='hora') return {...p,hora:hora(p)}; if(feature==='numerology') return input.name&&input.dob?calculateNumerology(input.name,input.dob):{status:'INPUT_REQUIRED',required:['name','dob']}; if(feature==='rahu-kaal') return p.rahuKaal; if(feature==='tithi') return p.tithi; if(feature==='vaar') return p.vara; if(feature==='karana') return p.karana; if(feature==='shubh-muhurat') return {abhijitMuhurta:p.abhijitMuhurta,brahmaMuhurta:p.brahmaMuhurta,vijayaMuhurta:p.vijayaMuhurta,godhuliMuhurta:p.godhuliMuhurta,nishitaKaal:p.nishitaKaal}; return p; }

export function buildHoroscope(period,date,sign){ let base=dateObj(date); if(period==='monthly') base=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth(),1)); if(period==='yearly') base=new Date(Date.UTC(base.getUTCFullYear(),0,1)); let count=period==='weekly'?7:period==='monthly'?new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,0)).getUTCDate():period==='yearly'?12:1; const days=[]; for(let i=0;i<count;i++){const d=period==='yearly'?new Date(Date.UTC(base.getUTCFullYear(),i,1)):new Date(base.getTime()+i*86400000); const jd=julianDay(d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate(),0); days.push(buildDailyHoroscope(jd));} const signs=sign?[sign]:Object.keys(days[0].horoscopes); const result={period,start:date,days:days.length,sampling:period==='yearly'?'first day of each month':'daily',horoscopes:{}}; for(const s of signs){const rows=days.map(d=>d.horoscopes[s]).filter(Boolean); result.horoscopes[s]={sign:s,scores:rows.map(r=>r.score),averageScore:Number((rows.reduce((a,r)=>a+r.score,0)/rows.length).toFixed(2)),bestScore:Math.max(...rows.map(r=>r.score)),lowestScore:Math.min(...rows.map(r=>r.score)),grades:[...new Set(rows.map(r=>r.grade))],daily:period==='daily'?rows:undefined};} return result; }
