/**
 * Canonical master report organization derived from the supplied 80-section
 * report outline. This is presentation metadata only; it never invents
 * calculations. Existing report sections remain intact.
 */
export const MASTER_REPORT_OUTLINE = Object.freeze([
  ['1','Basic Details',['Person Details','Avkahada Chakra']],
  ['2','Ghatak & Favourable Points',['Ghatak (Malefics)','Favourable Points']],
  ['3','Planetary Position',['Current Dasha','Planets & Positions','Planet Parameters','Charts']],
  ['4','Chalit Table & Chart',['Chalit Table','Chalit Chart']],
  ['5','Key Points For Your Kundli',['Core Traits']],
  ['6','Your Ascendant',['Ascendant Explanation','Health','Temperament & Personality','Physical Appearance']],
  ['7','Moon Sign',['Moon Sign Explanation','Health','Temperament & Personality','Physical Appearance']],
  ['8','Your Nakshatra',['Nakshatra Explanation','Nakshatra Prediction','Education & Income','Family Life']],
  ['9','Panchang Predictions',['Tithi','Weekday','Yoga','Karan','Nakshatra']],
  ['10','General Prediction',['Character','Happiness And Fulfillment','Life Style','Career','Occupation','Health','Hobbies','Love Matters','Finance','Education']],
  ['11','Planet Consideration in Astrology',['Sun Consideration']],
  ['12','Planetary Consideration (Continued)',['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu']],
  ['13','Planetary Yogas & Combinations',['Auspicious Yogas','Inauspicious Yogas / Doshas']],
  ['14','Detailed House Analysis (12 Bhavas)',['1st House','2nd House','3rd House','4th House','5th House','6th House','7th House','8th House','9th House','10th House','11th House','12th House']],
  ['15','Dasha Analysis & Timelines',['Vimshottari Dasha Overview','Mahadasha Periods','Antardasha Breakdown','Dasha Predictions']],
  ['16','Transits (Gochara)',['Major Planet Transits','Special Transit Effects']],
  ['17','Remedial Measures (Upay)',['Gemstone Recommendation','Rudraksha Suggestion','Mantra & Chanting','Yantra Recommendation','Charity & Fasting']],
  ['18','Division Charts (Shodashvarga / Varga Charts)',['D-1','D-2','D-3','D-4','D-7','D-9','D-10','D-12','D-16','D-20','D-24','D-27','D-30','D-40','D-45','D-60']],
  ['19','Planetary Strengths & Mathematical Calculations',['Shadbala Breakdown','Bhava Bala','Ashtakvarga System','Varga Bheda & Avasthas','Special Points & Lagnas']],
  ['20','Planetary Aspects & Relationships',['Planetary Aspects','Maitri Chakra']],
  ['21','K.P. (Krishnamurti Paddhati) System',['KP Planetary Positions','KP Cuspal Positions','KP House Significators','KP Ruling Planets']],
  ['22','Jaimini Astrology Calculations',['Jaimini Karakas','Jaimini Chara Dasha']],
  ['23','Annual Horoscope (Varshaphala / Tajika System)',['Varsha Chart','Tajika Yogas','Patyayini Dasha']],
  ['24','Matchmaking & Compatibility (Ashtakoot Guna Milan)',['Guna Scoring','Dosha Analysis']],
  ['25','Lal Kitab System (Red Book Predictions)',['Lal Kitab Planet Positions','Lal Kitab Debts','Lal Kitab Yearly Chart']],
  ['26','Numerology Analysis (Ank Jyotish)',['Core Numbers','Numerical Predictions']],
  ['27','Ashtakvarga Deep-Dive Calculations',['Trikona Shodhana','Ekadhipatya Shodhana','Pinda Sadhana']],
  ['28','Transit (Gochara) Timing & Kakshya Analysis',['Transit Timing','Kakshya System']],
  ['29','Specialty & Medical Astrology',['Health & Medical Predictions','Career & Business Suitability']],
  ['30','Prashna Kundli (Horary Astrology)',['Prashna Time Details','Query Outcome']],
  ['31','Muhurat & Panchang Elements',['Auspicious Muhurats','Inauspicious Timings']],
  ['32','Planetary Yogas (Extended List)',['Special Combinations']],
  ['33','Planetary Longitudes & Cusp Details (Extended)',['Planetary Longitudes','Bhava Madhya & Sandhi']],
  ['34','Sub-Dasha Breakdown (5-Tier Dasha)',['Pratyantardasha','Sookshma Dasha','Prana Dasha']],
  ['35','Specialty Varga Sub-Tables',['Varga Bhedas','Vaisheshikamsa Strengths','Graha Avasthas']],
  ['36','Mathematical Ashtakvarga Tables',['Individual Bhinnashtakvarga Tables','Sarvashtakvarga Matrix']],
  ['37','Planetary Aspects Matrix (Drishti Table)',['Direct Aspects Table','Special Aspect Strength','Aspect Matrix Score']],
  ['38','Jaimini Sub-Calculations & Char Dasha',['Karakamsha Analysis','Upapada Lagna','Jaimini Aspect Rules']],
  ['39','Specific Dosha Nullifications & Exceptions',['Mangal Dosha Exceptions','Kaal Sarp Variations','Pitra Dosha Causes']],
  ['40','Upagrahas & Special Mathematical Points',['Gulika & Mandi','Other Upagrahas','Special Mathematical Lagnas']],
  ['41','Comprehensive Transit Analysis (Gochara Deep-Dive)',['Ashtakvarga Transit Overlay','Vedha Positions','Tara Bala & Chandra Bala','Sadesati Phases Breakdown']],
  ['42','Nadi & Stellar Astrology (Nakshatra Nadi System)',['Sub-Sub-Sub Lord Sequence','Nakshatra Padas & Stars','Nadi Combinations']],
  ['43','Special Lagnas & Mathematical Sensitive Points',['Arudha Padas','Hora Lagna','Ghatika Lagna','Indu Lagna','Shree Lagna']],
  ['44','Upagraha & Aprakash Graha (Shadow Planets & Points)',['Gulika & Mandi Calculations','Dhuma, Vyatipata, Parivesha','Indrachapa & Upaketu']],
  ['45','Medical Astrology & Body Part Mapping',['Anatomy by Houses','Planetary Disease Factors','Tri-Dosha Balance']],
  ['46','Varshaphala & Annual Chart (Tajika System Extended)',['Annual Sahams','Tri-Pataki Chakra','Annual Planet Strengths']],
  ['47','Detailed Matchmaking (Guna Milan & Beyond)',['Ashtakoot Score Breakdown','Dashakoot System','Papasamya Comparison']],
  ['48','Fasting, Worship & Daily Rituals (Vrat & Upasana)',['Daily Deity Worship','Vrat Rules','Mantra Japa Guidelines']],
  ['49','Prashna (Horary) & Nimitta System',['Prashna Lagna & Arudha','Omens & Nimitta','Karya Siddhi Indicators']],
  ['50','Panchang Calculations & Micro-Elements',['Tithi & Paksha Details','Nakshatra & Pada Division','Yoga & Karan Analysis','Vara & Hora Timings']],
  ['51','Nakshatra Tara Chakra & Navatara',['Janma Tara','Sampat, Vipat, Kshema, Pratyak','Sadhana, Naidhana, Mitra, Param Mitra']],
  ['52','Sarvatobhadra Chakra & Special Chakras',['Sarvatobhadra Chakra Overlay','Kota Chakra','Sudarshana Chakra','Kurma Chakra']],
  ['53','Advanced Mathematical Metrics',['Ayanamsa Precision','Julian Day Number','Obliquity of Ecliptic','Sidereal Time']],
  ['54','Comprehensive Remedial Summary',['Color Therapy','Directional Remedies','Element Balancing','Customized Ritual Protocols']],
  ['55','Ashtakvarga Mathematical Reductions & Pinda Sadhana',['Trikona Shodhana Steps','Ekadhipatya Shodhana Rules','Shodya Pinda Calculations','Gochara Evaluation via Ashtakvarga']],
  ['56','Planetary Avasthas (Detailed Conditions)',['Baladi','Jagradadi','Deeptadi','Lajjitadi']],
  ['57','Comprehensive Upagraha Calculations',['Sun-Based Shadow Planets','Time-Based Shadow Planets','Upagraha House Placement']],
  ['58','Specialized Jaimini Systems',['7 vs 8 Karaka Schemes','Jaimini Aspect System','Jaimini Padas','Jaimini Dasha Variations']],
  ['59','Alternative Dasha Systems (Conditional Dashas)',['Ashtottari','Shodashottari','Dwisaptati Sama','Shatabdika','Chaturashiti Sama','Panchottari','Yogini','Kalachakra']],
  ['60','Specialized Panchang & Muhurat Factors',['Ghati / Pal / Vipala','Anandadi Yogas','Nitya Yogas & Karanas','Panchaka Analysis','Bhadra (Vishti Karana)']],
  ['61','Extended Divisional Charts (Varga Sub-Details)',['D-81','D-108','D-144']],
  ['62','Technical Astronomical Ephemeris Parameters',['True vs Mean Nodes','Equation of Time','Geocentric vs Topocentric','Right Ascension & Declination']],
  ['63','Varshaphala (Tajika System) Sub-Calculations',['Tajika Aspect System','16 Tajika Yogas','Sahams (36 Sensitive Points)','Pancha-Vargiya Bala','Varsheshwara Selection Rules']],
  ['64','Lal Kitab Advanced Structural Metrics',['Pucche & Soya Bhavas','Dharmi & Kurbani Planets','Lal Kitab Aspect System','Lal Kitab Varshaphala Rules']],
  ['65','Complete Nakshatra Level Breakdown',['Nakshatra Deities & Symbols','Nakshatra Attributes','Sub-Level Division']],
  ['66','Nadi Astrology Specialized Metrics',['Bhrigu Nandi Nadi Links','Karma Indexing','Transit Nadi Interlocking']],
  ['67','Sudarshana Chakra & Multi-Lagna System',['Surya Lagna Alignment','Chandra Lagna Alignment','Lagna Alignment','Combined Sudarshana Grid']],
  ['68','Specialized Upay & Ritual Parameters',['Mantra Recitation Protocol','Deity Worship Guidelines','Gemstone Wearing Rules','Daan (Charity) Items']],
  ['69','Ashtakvarga Deep-Dive Calculations & Application',['Individual Bhinnashtakvarga Matrix','Kakshya Division System','Ashtakvarga Kakshya Orbit Evaluation','Sarvashtakvarga Bindu Analysis','Samudaya Ashtakvarga']],
  ['70','Advanced Planetary Avasthas & Status Mechanics',['Baladi Avastha System','Jagradadi Avastha System','Deeptadi Avastha System','Lajjitadi Avastha System','Sayanadi Avastha System']],
  ['71','Upagraha & Non-Luminous Points (Aprakash Grahas)',['Sun-Based Shadow Points','Time-Based Shadow Points','Upagraha House Coordinates','Upagraha Aspect Strength']],
  ['72','Extended Divisional Charts (Higher Varga System)',['D-72','D-81','D-108','D-144']],
  ['73','Conditional & Special Dasha Systems',['Ashtottari','Shodashottari','Dwisaptati Sama','Shatabdika','Chaturashiti Sama','Panchottari','Yogini','Kalachakra']],
  ['74','Classical Astronomical & Ephemeris Adjustments',['True Node vs Mean Node','Topocentric vs Geocentric','Ayanamsa Precision Systems','Equation of Time','Sidereal Time at Birth','Julian Day Number']],
  ['75','Extended Jaimini System Calculations',['7 vs 8 Karaka Schemes','Jaimini Aspect Rules','Arudha Padas (A1 to A12)','Jaimini Rashi Dashas']],
  ['76','Specialized Varshaphala (Tajika System) Metrics',['16 Tajika Yogas','Annual Saham Points (36 Points)','Pancha-Vargiya Bala Table','Varsheshwara Selection Rules','Tri-Pataki Chakra System']],
  ['77','Lal Kitab Specialized Mechanics',['Pucche & Soya Bhavas','Dharmi & Kurbani Planets','Lal Kitab Unique Aspects','Lal Kitab Debt Rules (Rina)','Lal Kitab Planet Neutralization']],
  ['78','Krishnamurti Paddhati (KP System) Specialized Details',['Sub-Sub Lord & Sub-Sub-Sub Lord Mapping','House Cuspal Links','KP Ruling Planets (RP)','Horary (KP Prashna) Number']],
  ['79','Nadi Astrology Specialized Metrics',['Bhrigu Nandi Nadi Inter-relations','Karmic Indexing Rules','Nadi Transit Interlocking']],
  ['80','Comprehensive Remedial & Ritual Technicals',['Mantra Protocols','Gemstone Technicals','Charity (Daan) Protocols','Yantra Setup Protocols']],
]);
export function masterOutlineText(){ return MASTER_REPORT_OUTLINE.map(([n,t,items])=>`${n}. ${t}\n   ${items.map(x=>'• '+x).join('\n   ')}`).join('\n'); }
