/** Minimal dependency-free A4 PDF writer for HoraSaar reports. */
const PAGE_W = 595, PAGE_H = 842, M = 42;
const esc = s => String(s ?? '').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E\n\r\t]/g,'?');
const wrap = (s, max) => {
  const words = String(s ?? '').split(/\s+/); const lines=[]; let line='';
  for (const w of words) { if (!w) continue; const n=line ? line+' '+w : w; if(n.length>max && line){lines.push(line); line=w;} else line=n; }
  if(line) lines.push(line); return lines.length ? lines : [''];
};
const flatten = (v, depth=0) => {
  if (v === null || v === undefined) return 'Not available';
  if (typeof v !== 'object') return String(v);
  if (depth > 3) return '[nested data]';
  if (Array.isArray(v)) return v.slice(0,30).map(x=>flatten(x,depth+1)).join(' | ');
  return Object.entries(v).slice(0,50).map(([k,x])=>`${k}: ${flatten(x,depth+1)}`).join(' ; ');
};

export class SimplePdfWriter {
  constructor({title='HoraSaar Report', author='HoraSaar'}={}) { this.title=title; this.author=author; this.pages=[]; this.ops=[]; this.pageNo=0; }
  beginPage(){ this.ops=[]; this.pageNo++; }
  endPage(){ this.pages.push(this.ops.join('\n')); }
  op(s){this.ops.push(s);}
  text(x,y,size,s,{bold=false}= {}) { this.op(`BT /${bold?'F2':'F1'} ${size} Tf ${x} ${y} Td (${esc(s)}) Tj ET`); }
  line(x1,y1,x2,y2){this.op(`${x1} ${y1} m ${x2} ${y2} l S`);}
  rect(x,y,w,h){this.op(`${x} ${y} ${w} ${h} re S`);}
  heading(title,level=1){ const size=level===1?17:level===2?12:10; const y=this.cursor; this.text(M,y,size,title,{bold:true}); this.cursor-=size+7; this.line(M,this.cursor,PAGE_W-M,this.cursor); this.cursor-=10; this.ensure(40); }
  paragraph(s,{size=9,leading=12,indent=0,maxChars=95}={}){ for(const l of wrap(s,maxChars)){this.ensure(leading+25); this.text(M+indent,this.cursor,size,l); this.cursor-=leading;} this.cursor-=4; }
  kv(k,v){ this.ensure(28); const lines=wrap(`${k}: ${flatten(v)}`,100); for(let i=0;i<lines.length;i++){this.text(M,this.cursor,8.5,lines[i],{bold:i===0}); this.cursor-=11;} this.cursor-=2; }
  table(headers,rows){
    const cols=headers.length; const widths=Array.from({length:cols},(_,i)=>Math.max(8, Math.min(28, headers[i].length+2, ...rows.slice(0,40).map(r=>String(r[i]??'').length+2))));
    const total=widths.reduce((a,b)=>a+b,0); const scale=(PAGE_W-2*M)/total; const ws=widths.map(w=>w*scale); const chars=ws.map(w=>Math.max(7,Math.floor(w/4.5)));
    const rowLines=(row)=>Math.max(...row.map((v,i)=>wrap(flatten(v),chars[i]).length),1);
    const drawRow=(row,bold=false)=>{ const n=rowLines(row); const h=Math.max(18,n*9+6); this.ensure(h+8); let x=M; for(let i=0;i<cols;i++){this.rect(x,this.cursor-h,ws[i],h); const ls=wrap(flatten(row[i]),chars[i]); for(let j=0;j<Math.min(ls.length,4);j++) this.text(x+3,this.cursor-11-j*9,6.7,ls[j],{bold}); x+=ws[i];} this.cursor-=h; };
    drawRow(headers,true); for(const r of rows) drawRow(r,false); this.cursor-=8;
  }
  pre(s){ for(const raw of String(s??'').split('\n')){this.ensure(10); this.text(M,this.cursor,6.5,raw.slice(0,110)); this.cursor-=8;} this.cursor-=5; }
  ensure(n){ if(this.cursor-n < 55) this.newPage(); }
  newPage(){ if(this.pageNo) this.endPage(); this.beginPage(); this.cursor=PAGE_H-58; this.header(); }
  header(){ this.text(M,PAGE_H-28,8,'HORASAAR', {bold:true}); this.text(PAGE_W-M-130,PAGE_H-28,7,`Authentic Report | Page ${this.pageNo}`); this.line(M,PAGE_H-35,PAGE_W-M,PAGE_H-35); }
  footerAll(){ for(let i=0;i<this.pages.length;i++){ /* footer is injected by content object later */ } }
  addSection(sec){
    this.ensure(80); this.heading(sec.title,1);
    if(sec.pre) for(const p of sec.pre) this.pre(p);
    if(sec.rows) for(const [k,v] of sec.rows) this.kv(k,v);
    if(sec.table) this.table(sec.table.headers,sec.table.rows);
    if(sec.blocks) for(const b of sec.blocks){ this.heading(b.title,2); this.paragraph(b.body,{maxChars:105}); }
  }
  render(report){
    this.beginPage(); this.cursor=PAGE_H-58; this.header();
    this.text(M,this.cursor,23,'HoraSaar',{bold:true}); this.cursor-=31;
    this.text(M,this.cursor,14,'Authentic & Powerful Jyotish Report',{bold:true}); this.cursor-=22;
    this.paragraph('Calculation-first report generated by the HoraSaar application. Each section is assembled from the calculated chart result and configured datasets/rules. Missing or partial data is labelled rather than invented.',{size:10,leading:14,maxChars:85});
    this.kv('Generated',report.generatedAt); this.kv('Person',report.input?.name); this.kv('Birth place',report.input?.place); this.kv('Calculation fingerprint',report.fingerprint);
    this.heading('Report Contract',2); this.paragraph('Promise -> Activation -> Trigger -> Confirmation -> Contradiction -> Timing -> Outcome. Evidence score is not an empirical probability. A probability is displayed only when the calculation result explicitly marks it as empirically calibrated.');
    this.heading('Contents',2); report.sections.forEach((s,i)=>{this.ensure(14);this.text(M,this.cursor,8,`${i+1}. ${s.title}`);this.cursor-=11;});
    this.newPage();
    for(const s of report.sections){ this.addSection(s); }
    this.endPage();
    return this.toPdf();
  }
  toPdf(){
    const objs=[]; const add=x=>{objs.push(x);return objs.length;};
    const font1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
    const font2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
    const pagesId=add(''); const pageIds=[];
    for(const content of this.pages){ const stream=`q\n0.2 w\n${content}\nQ`; const sid=add(`<< /Length ${Buffer.byteLength(stream,'binary')} >>\nstream\n${stream}\nendstream`); const pid=add(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${sid} 0 R >>`); pageIds.push(pid); }
    objs[pagesId-1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] >>`;
    const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`); const info=add(`<< /Title (${esc(this.title)}) /Author (${esc(this.author)}) >>`);
    let out='%PDF-1.4\n%\xFF\xFF\xFF\xFF\n'; const offsets=[0];
    for(let i=0;i<objs.length;i++){offsets[i+1]=Buffer.byteLength(out,'binary');out+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`;}
    const xref=Buffer.byteLength(out,'binary'); out+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`; for(let i=1;i<=objs.length;i++) out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`; out+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R /Info ${info} 0 R >>\nstartxref\n${xref}\n%%EOF\n`; return Buffer.from(out,'binary');
  }
}
